# core/report_builder.py
"""
Report Builder — compiles all OSINT findings into an HTML report.
"""
import os
import json
from datetime import datetime
from utils.logger import get_logger
from config.settings import REPORT_OUTPUT_DIR

logger = get_logger("report_builder")

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DigitalTrace Report — {target}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Courier New', monospace; background: #0d1117; color: #c9d1d9; padding: 2rem; }}
  h1 {{ color: #58a6ff; font-size: 1.8rem; border-bottom: 1px solid #30363d; padding-bottom: 1rem; margin-bottom: 1.5rem; }}
  h2 {{ color: #79c0ff; font-size: 1.1rem; margin: 2rem 0 0.8rem; text-transform: uppercase; letter-spacing: 2px; }}
  .meta {{ color: #8b949e; font-size: 0.85rem; margin-bottom: 2rem; }}
  .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1.2rem; margin-bottom: 1rem; }}
  .found {{ color: #3fb950; font-weight: bold; }}
  .not-found {{ color: #8b949e; }}
  .breach {{ color: #f85149; font-weight: bold; }}
  .safe {{ color: #3fb950; }}
  .label {{ color: #8b949e; font-size: 0.8rem; text-transform: uppercase; margin-right: 0.5rem; }}
  .dork {{ background: #0d1117; padding: 0.4rem 0.8rem; border-left: 3px solid #58a6ff; margin: 0.3rem 0; font-size: 0.85rem; }}
  table {{ width: 100%; border-collapse: collapse; }}
  td, th {{ padding: 0.5rem; text-align: left; border-bottom: 1px solid #21262d; font-size: 0.9rem; }}
  th {{ color: #8b949e; font-size: 0.75rem; text-transform: uppercase; }}
  .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 20px; font-size: 0.75rem; }}
  .badge-green {{ background: #1b4332; color: #3fb950; }}
  .badge-red   {{ background: #3d1a1a; color: #f85149; }}
  .badge-grey  {{ background: #21262d; color: #8b949e; }}
  footer {{ margin-top: 3rem; color: #484f58; font-size: 0.8rem; text-align: center; }}
</style>
</head>
<body>
<h1>🔍 DigitalTrace — Investigation Report</h1>
<div class="meta">
  <span class="label">Target:</span>{target} &nbsp;|&nbsp;
  <span class="label">Generated:</span>{timestamp} &nbsp;|&nbsp;
  <span class="label">⚠ For authorized/educational use only</span>
</div>

{sections}

<footer>Generated by DigitalTrace OSINT Tool — For authorized security research only.</footer>
</body>
</html>"""

def _username_section(data: list) -> str:
    if not data:
        return ""
    rows = ""
    for r in data:
        badge = '<span class="badge badge-green">FOUND</span>' if r["found"] else '<span class="badge badge-grey">NOT FOUND</span>'
        link = f'<a href="{r["url"]}" style="color:#58a6ff">{r["url"]}</a>' if r["found"] else r["url"]
        rows += f"<tr><td>{r['platform']}</td><td>{link}</td><td>{badge}</td></tr>"
    return f"""
<h2>👤 Username Check</h2>
<div class="card">
<table>
<tr><th>Platform</th><th>URL</th><th>Status</th></tr>
{rows}
</table>
</div>"""

def _whois_section(data: dict) -> str:
    if not data or "error" in data:
        return ""
    rows = "".join(f"<tr><td class='label'>{k}</td><td>{v}</td></tr>" for k, v in data.items())
    return f"""
<h2>🌐 WHOIS / Domain Info</h2>
<div class="card"><table>{rows}</table></div>"""

def _breach_section(data: dict) -> str:
    if not data or "error" in data:
        return ""
    if not data.get("breached"):
        return f"""
<h2>🔒 Breach Check</h2>
<div class="card"><span class="safe">✅ No breaches found for {data['email']}</span></div>"""
    breaches_html = "".join(
        f"<div class='card'><strong class='breach'>{b['name']}</strong> ({b['domain']}) — {b['breach_date']}<br>"
        f"<span class='label'>Data types:</span> {', '.join(b['data_types'])}</div>"
        for b in data["breaches"]
    )
    return f"""
<h2>🚨 Breach Check — {data['breach_count']} breach(es) found</h2>
{breaches_html}"""

def _ip_section(data: dict) -> str:
    if not data or "error" in data:
        return ""
    rows = "".join(f"<tr><td class='label'>{k}</td><td>{v}</td></tr>" for k, v in data.items())
    return f"""
<h2>📡 IP Intelligence</h2>
<div class="card"><table>{rows}</table></div>"""

def _dork_section(data: dict) -> str:
    if not data:
        return ""
    sections = ""
    for cat, queries in data.items():
        dorks = "".join(f"<div class='dork'>{q}</div>" for q in queries)
        sections += f"<div class='card'><strong>{cat.replace('_',' ').title()}</strong>{dorks}</div>"
    return f"<h2>🔎 Google Dork Queries</h2>{sections}"

def _metadata_section(data: dict) -> str:
    if not data or "error" in data:
        return ""
    rows = "".join(f"<tr><td class='label'>{k}</td><td>{v}</td></tr>" for k, v in data.items())
    return f"""
<h2>📄 File Metadata</h2>
<div class="card"><table>{rows}</table></div>"""

def build_report(target: str, findings: dict) -> str:
    """
    Build and save an HTML report from collected findings.
    findings keys: username, whois, breach, ip, dorks, metadata
    """
    sections = ""
    sections += _username_section(findings.get("username", []))
    sections += _whois_section(findings.get("whois", {}))
    sections += _breach_section(findings.get("breach", {}))
    sections += _ip_section(findings.get("ip", {}))
    sections += _dork_section(findings.get("dorks", {}))
    sections += _metadata_section(findings.get("metadata", {}))

    html = HTML_TEMPLATE.format(
        target=target,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        sections=sections
    )

    os.makedirs(REPORT_OUTPUT_DIR, exist_ok=True)
    safe_target = target.replace("/", "_").replace(".", "_")
    filename = f"{REPORT_OUTPUT_DIR}/report_{safe_target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"

    with open(filename, "w") as f:
        f.write(html)

    logger.info(f"Report saved: {filename}")
    return filename
